# -*- coding: utf-8 -*-
"""llm_query.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWJG5HGT3omdGndEPR2nA_llj8YUq59u
"""

!pip install faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

model = SentenceTransformer("all-MiniLM-L6-v2")

def create_embd(text):

  return model.encode(text)

dimension = 384

index = faiss.IndexFlatL2(dimension)

documents = []
metadata_store = []

def store_summary(summary, timestamp, segment_id):

    embedding = create_embd(summary)

    index.add(
        np.array([embedding]).astype("float32")
    )

    documents.append(summary)

    metadata_store.append({
        "timestamp": timestamp,
        "segment_id": segment_id
    })

def retrieve(query, k=2):

    query_embedding = create_embd(query)

    distances, indices = index.search(
        np.array([query_embedding]).astype("float32"),
        k
    )

    results = []

    for i in indices[0]:

        results.append({

            "summary": documents[i],
            "metadata": metadata_store[i]

        })

    return results

# faiss.write_index(index, "video_index.faiss")
# index = faiss.read_index("video_index.faiss")
# import pickle

# with open("metadata.pkl", "wb") as f:

#     pickle.dump(
#         (documents, metadata_store),
#         f
#     )
# with open("metadata.pkl", "rb") as f:

#     documents, metadata_store = pickle.load(f)

