# -*- coding: utf-8 -*-
"""hawk_vision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cg2cRPWjfxqDCOCg4DagK0Qmanz7kK3H
"""

import torch
from transformers import AutoProcessor, Idefics3ForConditionalGeneration
from transformers.image_utils import load_image

# Cell 2 — Load Model
DEVICE = "cuda"

model_id = "HuggingFaceTB/SmolVLM-500M-Instruct"

processor = AutoProcessor.from_pretrained(model_id)

model = Idefics3ForConditionalGeneration.from_pretrained(
    model_id,
    torch_dtype=torch.float16
    ,
    _attn_implementation="eager"
).to(DEVICE)

model.eval()
print("Model loaded on:", next(model.parameters()).device)

def query_model(image_input, prompt_text="Describe this image", max_tokens=50):
    device = next(model.parameters()).device

    if isinstance(image_input, str):
        image = load_image(image_input)
    else:
        image = image_input

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image"},
                {"type": "text", "text": prompt_text}
            ]
        }
    ]

    prompt = processor.apply_chat_template(messages, add_generation_prompt=True)

    inputs = processor(
        text=prompt,
        images=[image],
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        output_ids = model.generate(**inputs, max_new_tokens=max_tokens)

    output_ids = output_ids[:, inputs["input_ids"].shape[1]:]

    return processor.batch_decode(output_ids, skip_special_tokens=True)[0]

response = query_model(
    "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",
    "What do you see in the image ?")

print(response)
